### ISSUE TITLE
Supported file types list? 

### ISSUE THREAD

**Issue by foxnoodles** [itsWindows11/TowPad#1]
Would be nice to have it. Does it support .doc files for example?

**Comment by itsWindows11** [comment]
Currently supports .txt and .rtf as you can see when opening a file from the File menu in the app.

**Comment by foxnoodles** [comment]
> Currently supports .txt and .rtf as you can see when opening a file from the File menu in the app.

I didn't install it, usually you read the features of the app before deciding to install.
